### ISSUE TITLE
Nice one :)

### ISSUE THREAD

**Issue by FGRibreau** [italoacasas/redis-middleware#2]
Nice one @italoacasas!

This express middleware will be shared in our next [RedisWeekly](http://redisweekly.com/)! Once published (in a matter of minutes) you will be able to see your [projet description here](http://redisweekly.com/archive/139.html) :)

**Comment by italoacasas** [comment]
Thank you.

![giphy](https://cloud.githubusercontent.com/assets/6354455/14192079/89a62f26-f769-11e5-8f3f-85f6b933e9bc.gif)
